// const pcvalid = [
//     {
//         id:1,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:2,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:3,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:4,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:5,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:6,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:7,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
//     {
//         id:8,
//         img: '../../assets/images/42.png',
//         name: 'PC Gaming E-Power F1650',
//         price: '$349.95',
//         vote: 4.9,
//     },
// ]